# Generated by Django 4.2.13 on 2024-06-15 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttractionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("crowded_month", models.CharField(default="Jan", max_length=100)),
                ("time_to_visit", models.CharField(default="", max_length=100)),
                ("airport", models.CharField(default="", max_length=200)),
                ("rlwy_station", models.CharField(default="", max_length=200)),
                ("bus_station", models.CharField(default="", max_length=200)),
                ("duration", models.IntegerField(default=0)),
                ("lat", models.FloatField(default=0)),
                ("lng", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SuitableFor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Thing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("latitude", models.FloatField(default=0)),
                ("longitude", models.FloatField(default=0)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.city"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.country"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("duration", models.IntegerField(default=0)),
                ("visit_fare", models.IntegerField(default=0)),
                ("time_to_visit", models.CharField(default="", max_length=200)),
                ("opening_hrs", models.CharField(default="", max_length=100)),
                ("book_process", models.CharField(default="", max_length=100)),
                ("rating", models.FloatField(default=4)),
                ("alert", models.CharField(default="", max_length=400)),
                ("events", models.CharField(default="", max_length=400)),
                ("lat", models.FloatField(default=0)),
                ("lng", models.FloatField(default=0)),
                (
                    "attraction_type",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.attractiontype",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.city"
                    ),
                ),
                ("suitable_for", models.ManyToManyField(to="api.suitablefor")),
            ],
        ),
        migrations.CreateModel(
            name="FoodPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("restaurant", "Restaurant"),
                            ("cafe", "Cafe"),
                            ("bar", "Bar"),
                            ("street_food", "Street Food"),
                        ],
                        max_length=20,
                    ),
                ),
                ("lat", models.FloatField(default=0)),
                ("lng", models.FloatField(default=0)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.city"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.state"
            ),
        ),
    ]
